from typing import Any, List

class IntMenu:
    def __new__(cls, prompt: str, min_value: int, max_value: int) -> int: ...

class MultipleChoiceMenu:
    def __new__(cls, prompt: str, options: List[Any]) -> int: ...

class CheckboxMenu:
    def __new__(cls, prompt: str, options: List[Any]) -> int: ...

class FreeformMenu:
    def __new__(cls, prompt: str) -> str: ...